### ISSUE TITLE
UTC time format

### ISSUE THREAD

**Issue by BigWebstas** [jwoglom/dm2nsc#3]
Any way to get it to write to the mongodb using UTC time? for some reason i cannot get xdrip to sync down from nightscout an entry that isnt in UTC time

**Comment by BigWebstas** [comment]
Might not be a UTC issue i think its the format that Arrow returns
this works - "created_at": "2019-07-23T19:47:42.625Z"
this doesn't - "created_at": "2019-07-22 22:09:00-06:00",
Maybe the "-" in the time?

![image](https://user-images.githubusercontent.com/2896329/61742402-45b52880-ad50-11e9-9570-d3c524aeafd5.png)

**Comment by jwoglom** [comment]
Interesting. I have definitely run into that xDrip error before, but from what I can tell it has always been transient for me. What versions of xDrip and Nightscout are you running? My guess is that maybe one or both of them subtly changed their date parsing logic, and while this date format used to work and get parsed correctly it's now being rejected due to stricter date/time format checking.

Maybe try modifying this line in dm2nsc to specify the exact time format which xDrip parses from nightscout? https://github.com/jwoglom/dm2nsc/blob/master/getdata.py#L69

**Comment by BigWebstas** [comment]
I am on the dev channel of Xdrip oe3274c-2019-07-25 and i have Nightscout ver 11

**Comment by BigWebstas** [comment]
I had another question in the other bug you mentioned  

> you likely will want to exclude that data from being re-imported back into Nightscout (This seems to be denoted by a "[Nightscout]" present at the end of the "notes" field in the D-M entry, you'd want to check for that and if so not append the dictionary to the list.)

I am racking my brain on how to accomplish this, i have tried searching the json entries for the word nightscout but it never seems to work, any help would be greatly appreciated 
my Diabetes:M is a duplicate notes nightmare
![image](https://user-images.githubusercontent.com/2896329/62087022-73511480-b21d-11e9-8208-5fd2ca9f6800.png)

**Comment by BigWebstas** [comment]
I think i have it figured out, thank you for your direction
